FROM golang:1.26-alpine
LABEL org.opencontainers.image.authors="Palo Alto Networks Idira™"
LABEL id="conjur-cli-go-junit-processor"

WORKDIR /test

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev \
               bash

# gocov converts native coverage output to gocov's JSON interchange format
# gocov-xml converts gocov format to XML for use with Jenkins/Cobertura
RUN go install github.com/jstemmer/go-junit-report@latest && \
    go install github.com/afunix/gocov/gocov@latest && \
    go install github.com/AlekSi/gocov-xml@latest
