FROM golang:1.13-stretch

RUN apt-get update && \
    apt-get install -y jq less vim

WORKDIR /go/src/github.com/cyberark/conjur-cli-go

RUN go get -u \
  github.com/derekparker/delve/cmd/dlv \
  github.com/golang/mock/gomock \
  github.com/golang/mock/mockgen \
  github.com/jstemmer/go-junit-report \
  github.com/smartystreets/goconvey \
  golang.org/x/lint/golint

RUN mkdir -p /go/src/github.com/cyberark/conjur-cli-go/output

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN ./bin/generate-mocks
