FROM golang:1.17-stretch

RUN apt-get update && \
    apt-get install -y jq less vim

WORKDIR /conjur-cli-go

RUN go get -u \
  github.com/derekparker/delve/cmd/dlv \
  github.com/golang/mock/gomock \
  github.com/golang/mock/mockgen \
  github.com/jstemmer/go-junit-report \
  golang.org/x/lint/golint

RUN mkdir -p /conjur-cli-go/output

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN ./bin/generate-mocks
