#!/bin/bash -ex

export CONJUR_ACCOUNT=cucumber
export CONJUR_AUTHN_LOGIN=admin

source functions.sh

function finish {
  docker-compose down -v
}
trap finish EXIT

function runTests() {
  local keys=( $(getKeys) )
  local api_key=${keys[0]}
  local api_key_v4=${keys[1]}
  local ssl_cert_v4="$(getCert)"
  local service=test

  docker-compose build --pull "$service"

  docker-compose run --rm \
    -e CONJUR_AUTHN_API_KEY="$api_key" \
    -e CONJUR_V4_AUTHN_API_KEY="$api_key_v4" \
    -e CONJUR_V4_SSL_CERTIFICATE="$ssl_cert_v4" \
    $service
}

function main() {
  echo "Starting Conjur..."
  startConjur

  echo "Initializing environment..."
  initEnvironment

  echo "Running tests..."
  runTests

  echo "Tests complete!"
}

main
