#!/usr/bin/env bash

set -eo pipefail

# Protect against this script running outside the cli-dev container
if [ ! -f /.dockerenv ] || [ -z "${GOPATH}" ]; then
    echo "This script should only be run inside the cli-dev container"
    exit 1
fi

# Navigate to the root directory of the repository to ensure we can run this script
# from anywhere.
cd "$(dirname "$0")"

# Ensure ~/.bashrc has been sourced
# shellcheck source=/dev/null
. ~/.bashrc

path_to_dot_netrc=~/.netrc
path_to_dot_conjurrc=~/.conjurrc

admin_api_key_value=$(admin_api_key)

echo
echo "Refreshing admin user connection details"

echo
echo "Admin API key: ${admin_api_key_value}"

cat <<EOL > "${path_to_dot_conjurrc}"
account: dev
appliance_url: http://conjur
EOL

echo "Wrote .conjurrc file to ${path_to_dot_conjurrc}"

cat <<EOL > "${path_to_dot_netrc}"
machine http://conjur/authn
        login admin
        password ${admin_api_key_value}
EOL

echo "Wrote .netrc file to ${path_to_dot_netrc}"
