#!/usr/bin/env bash

set -eo pipefail

# Navigate to the dev directory (where this script lives) to ensure we can run this script
# from anywhere.
cd "$(dirname "$0")"

# CC servers can't find it for some reason.  Local shellcheck is fine.
# shellcheck disable=SC1091
source "../ci/keycloak/keycloak_functions.sh"

# TODO: add a prompt and an -f flag to give the user control over destroying an already existing development environment.
# It can be such a pain to mistakenly destroy your environment.

ENABLE_OIDC_KEYCLOAK=false
ENABLE_OIDC_OKTA=false
ENABLE_OIDC_IDENTITY=false

# Minimal set of services.  We add to this list based on cmd line flags.
services=(pg conjur proxy cli-dev)

default_authenticators="authn"
enabled_authenticators="$default_authenticators"

main() {
  parse_options "$@"

  if docker-compose ps conjur | grep conjur >/dev/null 2>&1; then
    ./stop
  fi

  local conjur_account=dev
  local admin_initial_password='SuperSecret!!!!123'
  local path_to_admin_initial_password=tmp/admin_initial_password

  # Prepare tmp files
  echo
  echo "Preparing dev/tmp files"
  mkdir -p ./tmp
  touch ./tmp/.bashrc
  cat <<EOL > ./tmp/.bashrc
echo "Invoke dev_help to find out about the dev utilities available within this shell" >&2

function dev_help() {
  echo "
Available dev utilities
-----------------------

make: Make can be executed against the Makefile in the root directory of the repository.

      Available tasks are: run, build, install, test, integration.

admin_initial_password: Prints the initially-set password of the Conjur admin

admin_api_key: Prints the API key of the Conjur admin
"
}

function admin_initial_password() {
  cat ${PWD}/${path_to_admin_initial_password}
}

function admin_api_key() {
  curl -s 'http://conjur/dev?action=retrieve_api_key&role_id=dev:user:admin'
}

export -f admin_api_key
export -f admin_initial_password
EOL

  echo
  echo "Starting Containers"
  docker-compose up -d --no-deps "${services[@]}"

  echo
  docker-compose exec -T pg bash -e <<EOL
echo 'Waiting for Postgres to be ready...'
for i in {1..90}
do
  pg_isready -U postgres 2>&1 > /dev/null && echo ' Postgres is ready!' && exit 0;
  printf '.'
  sleep 1
done

echo 'Postgres is not ready after 90 seconds'
exit 1
EOL

  echo
  wait_for_conjur

  echo
  echo 'Setting up Conjur...'
  docker-compose exec -T conjur bundle exec rake "account:create_with_password[${conjur_account},${admin_initial_password}]"
  echo 'Finished setting up Conjur'

  echo
  echo "Admin password: ${admin_initial_password}"
  echo "${admin_initial_password}" | tr -d '\r\n' > "${path_to_admin_initial_password}"
  echo "Wrote admin password to dev/${path_to_admin_initial_password}"

  # Even when using OIDC, we need to set up conjur with the regular authenticator
  # so we can set up policy before dropping the user into the CLI container.
  docker-compose exec cli-dev ./dev/refresh-admin-connection-details

  echo
  echo "Loading policy"

  docker-compose exec -T conjur conjurctl policy load dev /dev/stdin < policy.yml

  echo
  echo "Setting up authenticators"

  init_oidc

  # Updates CONJUR_AUTHENTICATORS and restarts required services.
  start_auth_services
  
  echo
  echo "Entering CLI container"

  docker-compose exec cli-dev go mod download || true

  echo
  if [ "$ENABLE_OIDC_OKTA" = true ]; then
    echo "Setting up Conjur for OIDC (Okta)"
    docker-compose exec cli-dev bash -c 'conjur logout
conjur init --force-netrc --force -u http://conjur -i -a dev -t oidc --service-id okta-2
conjur login -i $OKTA_USERNAME -p $OKTA_PASSWORD'
  elif [ "$ENABLE_OIDC_KEYCLOAK" = true ]; then
    echo "Setting up Conjur for OIDC (Keycloak)"
    docker-compose exec cli-dev bash -c 'conjur logout
conjur init --force-netrc --force -u http://conjur -i -a dev -t oidc --service-id keycloak
conjur login -i alice -p alice'
  elif [ "$ENABLE_OIDC_IDENTITY" = true ]; then
    echo "Setting up Conjur for OIDC (Identity)"
  fi

  echo
  docker-compose exec cli-dev bash
}

parse_options() {
  while true ; do
    case "$1" in
      --oidc-keycloak ) ENABLE_OIDC_KEYCLOAK=true ; shift ;;
      --oidc-okta ) ENABLE_OIDC_OKTA=true ; shift ;;
      --oidc-identity ) ENABLE_OIDC_IDENTITY=true ; shift ;;
      # -h | --help ) print_help ; shift ;;
       * )
         if [ -z "$1" ]; then
           break
         else
           echo "$1 is not a valid option"
           exit 1
         fi ;;
    esac
  done
}

start_conjur_server() {
  echo "Starting Conjur server"
  docker-compose exec -d conjur conjurctl server

  echo 'Checking if Conjur server is ready'
  wait_for_conjur
}

wait_for_conjur() {
  docker-compose exec conjur conjurctl wait
}

client_load_policy() {
  local policy_file=$1

  docker-compose exec -T cli-dev conjur policy load -b root -f - < "$policy_file"
}

client_add_secret() {
  local variable=$1
  local value=$2

  docker-compose exec cli-dev conjur variable set -i "$variable" -v "$value"
}

configure_oidc_providers() {
  # Start conjur again, since it is recreating by docker-compose because of
  # dependency with keycloak
  start_conjur_server
  wait_for_keycloak_server
  fetch_keycloak_certificate
  configure_oidc_authenticators
  enable_oidc_authenticators
  create_keycloak_users
  echo "keycloak admin console url: http://0.0.0.0:7777/auth/admin"
}

configure_oidc_authenticators() {
    echo "Setting Keycloak policy and variables values in Conjur"
    client_load_policy "../ci/keycloak/policy.yml"

    client_add_secret 'conjur/authn-oidc/keycloak/provider-uri' 'https://keycloak:8443/auth/realms/master'
    client_add_secret 'conjur/authn-oidc/keycloak/client-id' 'conjurClient'
    client_add_secret 'conjur/authn-oidc/keycloak/client-secret' '1234'
    client_add_secret 'conjur/authn-oidc/keycloak/claim-mapping' 'email'
    client_add_secret 'conjur/authn-oidc/keycloak/redirect_uri' 'http://127.0.0.1:8888/callback'

    client_load_policy "../ci/keycloak/users.yml"

  if [[ $ENABLE_OIDC_OKTA = true ]]; then
    echo "Confuring Okta policy and variables values in Conjur"
    client_load_policy "../ci/okta/policy.yml"

    local okta_valid=true
    if [[ -z "$OKTA_PROVIDER_URI" ]]; then
      echo "OKTA_PROVIDER_URI is not set"
      okta_valid=false
    fi

    if [[ -z "$OKTA_CLIENT_ID" ]]; then
      echo "OKTA_CLIENT_ID is not set"
      okta_valid=false
    fi

    if [[ -z "$OKTA_CLIENT_SECRET" ]]; then
      echo "OKTA_CLIENT_SECRET is not set"
      okta_valid=false
    fi

    if [[ $okta_valid = true ]]; then
      # Replace these okta values with your own if not using Summon
      client_add_secret 'conjur/authn-oidc/okta-2/provider-uri' "${OKTA_PROVIDER_URI}oauth2/default"
      client_add_secret 'conjur/authn-oidc/okta-2/client-id' "$OKTA_CLIENT_ID"
      client_add_secret 'conjur/authn-oidc/okta-2/client-secret' "$OKTA_CLIENT_SECRET"
    else
      echo "Skipped Okta configuration due to missing environment variables"
    fi


    client_add_secret 'conjur/authn-oidc/okta-2/claim-mapping' 'preferred_username'
    client_add_secret 'conjur/authn-oidc/okta-2/redirect_uri' 'http://127.0.0.1:8888/callback'

    client_load_policy "../ci/okta/users.yml"
  fi
}

enable_oidc_authenticators() {
  echo "Configuring Keycloak as OpenID provider for automatic testing"
  # We enable an OIDC authenticator without a service-id to test that it's
  # invalid.
  enabled_authenticators="$enabled_authenticators,authn-oidc/keycloak"

  if [[ $ENABLE_OIDC_OKTA = true ]]; then
    echo "Configuring OKTA as OpenID provider for manual testing"
    enabled_authenticators="$enabled_authenticators,authn-oidc/okta-2"
  fi
}

init_oidc() {
  # # ADFS and OKTA make no sense without OIDC.
  # if [[ $EENABLE_OIDC_KEYCLOAK = false &&
  #   ($ENABLE_OIDC_ADFS = true || $ENABLE_OIDC_OKTA = true) ]]
  # then
  #   echo "Error: --oidc-adfs and --oidc-okta both require --oidc-keycloak"
  #   exit 1
  # fi

  if [[ $ENABLE_OIDC_KEYCLOAK != true ]]; then
    return
  fi

  services+=(keycloak)
  docker-compose up -d --no-deps "${services[@]}"

  configure_oidc_providers
}

start_auth_services() {
  echo "Setting CONJUR_AUTHENTICATORS to: $enabled_authenticators"
  env_args+=(-e "CONJUR_AUTHENTICATORS=$enabled_authenticators")

  # Will restart services if configuration has changed.  I think this happens
  # when additional authenticators are enabled.
  docker-compose up -d --no-deps "${services[@]}"

  # If that happens, we need to restart Conjur server.
  if [[ "$enabled_authenticators" != "$default_authenticators" ]]; then
    start_conjur_server
  fi
}

main "$@"
