#!/bin/bash -e

# Navigate to the dev directory (where this script lives) to ensure we can run this script
# from anywhere.
cd "$(dirname "$0")"

set -x

docker compose down -v --remove-orphans
rm -rf ./tmp/
