#!/bin/bash -ex

set -o pipefail

go clean -i

pkgs="$(go list ./...)"
go vet $pkgs
golint -set_exit_status $pkgs

go build -o conjur-cli-go cmd/conjur-cli/main.go
mv conjur-cli-go /usr/bin

go test -v $pkgs | tee /dev/stderr | go-junit-report > output/junit.xml
