#!/bin/bash -ex

set -o pipefail

go clean -modcache

./bin/check_linting

pkgs="$(go list ./...)"

go build -o conjur-cli-go cmd/conjur-cli/main.go
mv conjur-cli-go /usr/bin

go test -coverprofile=output/c.out -v $pkgs | tee /dev/stderr | go-junit-report > output/junit.xml
