#!/usr/bin/env bash
set -e

source "./shared.sh"

services=(pg conjur cli)

# set the COMPOSE_PROJECT_NAME for the tests you'll be running
COMPOSE_PROJECT_NAME="$(openssl rand -hex 3)"

export COMPOSE_PROJECT_NAME

cleanup_and_dump_logs() {
  echo "Cleaning up... Saving container logs in cleanup.log"
  docker-compose logs &> cleanup.log
  docker-compose rm --stop --force
}

trap 'cleanup_and_dump_logs' EXIT

function main() {

  local conjur_account=test
  local admin_initial_password='SuperSecret!!!!123'

  echo
  echo "Starting Containers"
  docker-compose up -d --no-deps "${services[@]}"

  echo
  _wait_for_pg pg

  echo
  wait_for_conjur

  echo
  echo 'Setting up Conjur...'
  docker-compose exec -T conjur bundle exec rake "account:create_with_password[${conjur_account},${admin_initial_password}]"
  echo 'Finished setting up Conjur'

  echo
  echo 'Setting up CLI as admin...'
  client_init_and_login "$conjur_account" "$admin_initial_password"

  echo
  echo 'Setting up Okta authenticator and resources...'
  init_okta

  docker-compose exec -T cli make integration
}

main
