#!/usr/bin/env bash
set -eox pipefail

# Navigate to the ci directory (where this script lives) to ensure we can run this script
# from anywhere.
cd "$(dirname "$0")"

source "./shared.sh"

services=(pg conjur proxy keycloak)

# set the COMPOSE_PROJECT_NAME for the tests you'll be running
COMPOSE_PROJECT_NAME="$(openssl rand -hex 3)"
export COMPOSE_PROJECT_NAME

cleanup_and_dump_logs() {
  echo "Cleaning up... Saving container logs in cleanup.log"
  docker-compose logs &> cleanup.log
  docker-compose rm --stop --force
}

trap 'cleanup_and_dump_logs' EXIT

function main() {

  local conjur_account=dev
  local admin_initial_password='SuperSecret!!!!123'

  echo
  echo "Starting Containers"
  docker-compose up -d --no-deps "${services[@]}"

  echo
  _wait_for_pg pg

  echo
  wait_for_conjur

  echo
  echo 'Setting up Conjur...'
  docker-compose exec -T conjur bundle exec rake "account:create_with_password[${conjur_account},${admin_initial_password}]"
  echo 'Finished setting up Conjur'

  echo
  echo 'Setting up Keycloak'
  configure_oidc_providers
  echo 'Finished setting up Keycloak'

  docker-compose run -T \
    -e PATH_TO_CONJUR_BINARY="${PWD}/../dist/goreleaser/conjur-cli-go_linux_amd64_v1/conjur" \
    test "${PWD}/../dist/goreleaser/integration_linux_amd64_v1/integration" -test.v -test.parallel=1 -test.count=1
}

main
